---
title: "STAT Capstone"
author: "Isaac Damon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(sf)
metros <- read_sf("Metro_Stations_in_DC.geojson")
crimes <- read_sf("Crime_Incidents_in_2025.geojson")
census <- read.csv("Census_ACS.csv")
```

```{r above}
# adding transfer stations and above below ground to metro stations
metros <-
  metros |>
  #The 2 represents an above and below ground station. We can decide what to do with that later
  mutate(Above_Ground = c(1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0),
         Transfer_Station = if_else(LINE == "red" |
                                      LINE == "green" |
                                    LINE == "green, yellow" |
                                      LINE == "blue, orange, silver" |
                                      LINE == "blue, silver" | 
                                      LINE == "orange",
                            0,
                            1))

#From looking at the map in DC, yellow and green are the same line
#orange, blue and silver are the same lines
#these won't be counted as transfer stations
```