---
title: "STAT 4810 Census ACS Data Fetch"
---

```{r}
pacman::p_load(
  tidyverse,
  tidycensus
)

readRenviron("~/.Renviron")
```

```{r}

crime_control_vars <- c(
  
  # --- Population / Exposure ---
  total_population = "B01003_001E",        # Total population
  total_housing_units = "B25001_001E",      # Housing units
  
  # --- Income & Poverty ---
  median_household_income = "B19013_001E",  # Median household income (past 12 months)
  population_below_poverty = "B17001_002E", # Population below poverty level
  
  # --- Employment ---
  unemployed_population = "B23025_005E",    # Unemployed population (16+ in labor force)
  
  # --- Education ---
  bachelors_degree = "B15003_022E",         # Bachelor's degree
  masters_degree = "B15003_023E",           # Master's degree
  professional_degree = "B15003_024E",      # Professional school degree
  doctorate_degree = "B15003_025E",         # Doctorate degree
  
  # --- Household Structure ---
  total_households = "B11001_001E",          # Total households
  single_parent_households = "B11001_006E",  # Female householder, no spouse present
  
  # --- Housing Tenure & Stability ---
  owner_occupied_units = "B25003_002E",     # Owner-occupied housing units
  renter_occupied_units = "B25003_003E",    # Renter-occupied housing units
  vacant_units = "B25002_003E",              # Vacant housing units
  median_gross_rent = "B25064_001E",         # Median gross rent
  
  # --- Race / Ethnicity (Structural Controls) ---
  non_hispanic_white = "B03002_003E",        # White alone, not Hispanic or Latino
  non_hispanic_black = "B03002_004E",        # Black or African American alone, not Hispanic or Latino
  hispanic_latino = "B03002_012E"             # Hispanic or Latino
)
```



```{r}
dc_acs_long <- get_acs(
  geography = "tract",
  variables = crime_control_vars,
  year = 2023,
  survey = "acs5",
  state = "DC",
  geometry = TRUE
) |> 
  bind_rows()
```


```{r}
new_vars <- c(
  # --- Population / Exposure ---
  total_population = "B01003_001",        # Total population
  total_housing_units = "B25001_001",      # Housing units
  # --- Income & Poverty ---
  median_household_income = "B19013_001",  # Median household income (past 12 months)
  population_below_poverty = "B17001_002", # Population below poverty level
  # --- Employment ---
  unemployed_population = "B23025_005",    # Unemployed population (16+ in labor force)
  # --- Education ---
  bachelors_degree = "B15003_022",         # Bachelor's degree
  masters_degree = "B15003_023",           # Master's degree
  professional_degree = "B15003_024",      # Professional school degree
  doctorate_degree = "B15003_025",         # Doctorate degree
  # --- Household Structure ---
  total_households = "B11001_001",          # Total households
  single_parent_households = "B11001_006",  # Female householder, no spouse present
  # --- Housing Tenure & Stability ---
  owner_occupied_units = "B25003_002",     # Owner-occupied housing units
  renter_occupied_units = "B25003_003",    # Renter-occupied housing units
  vacant_units = "B25002_003",              # Vacant housing units
  median_gross_rent = "B25064_001",         # Median gross rent
  # --- Race / Ethnicity (Structural Controls) ---
  non_hispanic_white = "B03002_003",        # White alone, not Hispanic or Latino
  non_hispanic_black = "B03002_004",        # Black or African American alone, not Hispanic or Latino
  hispanic_latino = "B03002_012"             # Hispanic or Latino
)
```


```{r}
dc_acs_wide <- 
  dc_acs_long |> 
  select(GEOID, NAME, variable, estimate, geometry) |> 
  pivot_wider(
    id_cols = c(GEOID, NAME, geometry),
    names_from = variable,
    values_from = estimate
  )
```


```{r}
sf::st_agr(dc_acs_wide) <- "constant"
```


```{r}
acs_final <- 
  dc_acs_wide |> 
  rename(!!!new_vars) |> 
  mutate(
    # Poverty Rate
    poverty_rate = population_below_poverty / total_population,
    # Unemployment Rate
    unemployment_rate = unemployed_population / total_population,
    # Education
    pct_bachelors_or_higher = (
      bachelors_degree + masters_degree + 
        professional_degree + doctorate_degree) / total_population,
    # Single Parent Houses
    pct_single_parent_households = single_parent_households / total_households,
    # Percentage Owned
    pct_owner_occupied = owner_occupied_units / total_housing_units,
    # Percentage Rented
    pct_renter_occupied = renter_occupied_units / total_housing_units,
    # Vacancy Rate
    vacancy_rate = vacant_units / total_housing_units,
    # White %
    pct_non_hispanic_white = non_hispanic_white / total_population,
    # Black %
    pct_non_hispanic_black = non_hispanic_black / total_population,
    # Hispanic / Latino %
    pct_hispanic_latino = hispanic_latino / total_population
  ) |> 
  select(GEOID, NAME, total_population, total_housing_units, median_household_income, poverty_rate,
         unemployment_rate, pct_bachelors_or_higher, pct_renter_occupied, vacancy_rate, 
         pct_non_hispanic_black, pct_hispanic_latino
  )
```


```{r}
tibble(acs_final)
```


```{r}
sf::st_write(acs_final, "Census_ACS.csv", layer_options = "GEOMETRY=AS_WKT")
sf::st_write(dc_acs_long, "Census_ACS_RAW.csv", layer_options = "GEOMETRY=AS_WKT")
```

